version: '3.8'
services:
  flask-app:
    build:
      context: .               
      dockerfile: Dockerfile   
    ports:
      - "5000:5000"           
    volumes:
      - .:/Aplicacion_Crud                 
    depends_on:
      - db                          
 
  db:
    image: mysql:8.0          
    environment:
      MYSQL_ROOT_PASSWORD: ramm160799  
      MYSQL_DATABASE: adtareas     
      MYSQL_USER: root             
      MYSQL_PASSWORD: ramm160799    
    ports:
      - "3306:3306"               