version: '3.8'
services:
  flask-app:
    build:
      context: .          
      dockerfile: Dockerfile   
    ports:
      - "5000:5000"
    volumes:
      - ./Aplicacion_Crud:/Aplicacion_Crud         
    environment:
      MYSQL_HOST: host.docker.internal 
      MYSQL_USER: root 
      MYSQL_PASSWORD: ramm160799
      MYSQL_DATABASE: adtareas  
