version: '3.8'
services:
  flask-app:
    build:
      context: .          
      dockerfile: Dockerfile   
    ports:
      - "5000:5000"
    volumes:
      - ./Aplicacion_Crud:/Aplicacion_Crud         
    depends_on:
      - db
    environment:
      MYSQL_HOST: db           
      MYSQL_USER: root 
      MYSQL_PASSWORD: ramm160799
      MYSQL_DATABASE: adtareas 

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ramm160799
      MYSQL_DATABASE: adtareas
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql  

volumes:
  db_data:
