version: '3.8'

services:
  flask-app:
    build:
      context: .          
      dockerfile: Dockerfile
    ports:
      - "5000:5000"       
    environment:
      MYSQL_HOST: host.docker.internal  # Apunta a la base de datos en el host
      MYSQL_USER: root    
      MYSQL_PASSWORD: ramm160799  
      MYSQL_DATABASE: adtareas
    volumes:
      - ./Aplicacion_Crud:/Aplicacion_Crud

